# Generated by Django 3.2 on 2021-04-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
