# Generated by Django 3.2 on 2021-04-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userblog', '0009_remove_profile_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
